language: java
jdk:
  - oraclejdk8

sudo: false

env:
  - GROUP=formatter
  - GROUP=index
  - GROUP=interning
  - GROUP=lock
  - GROUP=nullness-fbc
  - GROUP=nullness-raw
  - GROUP=regex
  - GROUP=signature
## This is just to determine the time to do the background build.
#  - GROUP=nothing

script: travis_wait 120 ./.travis-build.sh $GROUP

git:
  depth: 3
